version: "3.8"
services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./volume_data/sql_app.db:/app/sql_app.db
      - ./volume_data/privateFiles:/app/privateFiles
    depends_on:
      - redis
    ports:
      - "8000:8000"
  celery_worker:
    build: .
    volumes:
      - ./volume_data/sql_app.db:/app/sql_app.db
      - ./volume_data/privateFiles:/app/privateFiles
    command: celery -A src.config.celery_worker worker -l info --loglevel=debug -P eventlet
    depends_on:
      - redis
  flower:
    image: mher/flower
    command: ["celery", "--broker=redis://redis:6379", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
  redis:
    image: redis
